### ISSUE TITLE
Please help me out with the error.

### ISSUE THREAD

**Issue by Jarvis4555** [ramgsuri/car-booking-app#1]
```
PS C:\Users\1ando\Desktop\car-booking-app\ui> ng serve
: Error: ENOENT: no such file or directory, lstat 'C:\Users\1ando\Desktop\car-booking-app\ui\tsconfig.app.json'
    at Object.lstatSync (fs.js:1007:3)
    at calcProjectFileAndBasePath (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular\compiler-cli\src\perform_compile.js:114:31)
    at Object.readConfiguration (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular\compiler-cli\src\perform_compile.js:131:22)
    at Object.readTsconfig (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular-devkit\build-angular\src\angular-cli-files\utilities\read-tsconfig.js:25:29)
    at generateWebpackConfig (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:18:38)
    at generateBrowserWebpackConfigFromWorkspace (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:97:12)
    at Object.generateBrowserWebpackConfigFromContext (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:108:26)
    at async setup (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:70:37)

Error: : Error: ENOENT: no such file or directory, lstat 'C:\Users\1ando\Desktop\car-booking-app\ui\tsconfig.app.json'
    at Object.lstatSync (fs.js:1007:3)
    at calcProjectFileAndBasePath (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular\compiler-cli\src\perform_compile.js:114:31)
    at Object.readConfiguration (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular\compiler-cli\src\perform_compile.js:131:22)
    at Object.readTsconfig (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular-devkit\build-angular\src\angular-cli-files\utilities\read-tsconfig.js:25:29)
    at generateWebpackConfig (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:18:38)
    at generateBrowserWebpackConfigFromWorkspace (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:97:12)
    at Object.generateBrowserWebpackConfigFromContext (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:108:26)
    at async setup (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:70:37)

    at Object.readTsconfig (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular-devkit\build-angular\src\angular-cli-files\utilities\read-tsconfig.js:27:15)
    at generateWebpackConfig (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:18:38)
    at generateBrowserWebpackConfigFromWorkspace (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:97:12)
    at Object.generateBrowserWebpackConfigFromContext (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:108:26)
    at async setup (C:\Users\1ando\Desktop\car-booking-app\ui\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:70:37)

```

My Angular Version
```
Angular CLI: 8.0.6
Node: 12.18.4
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.6
@angular-devkit/core         8.0.6
@angular-devkit/schematics   8.0.6
@schematics/angular          8.0.6
@schematics/update           0.800.6
rxjs                         6.4.0
```

**Comment by ramgsuri** [comment]
Thanks a lot @Jarvis4555  for pointing the issue. 
Please take the latest pull, run npm install and then npm build, also I have checked-in tsconfig.app.json.
Also if this repository is helping you then feel free to rate this repository by providing stars and provide feedback and comments as well.
